### ISSUE TITLE
MVP review

### ISSUE THREAD

**Issue by antoniojgage** [chong0810/RandomPasswordGenerator#69]
1. scripts.js should go in assets
1. I'm not sure if the graders will take off for not using a confirm dialog for the other entries rather than the prompt. I'd look at this just in case.
1. the do/while loop setup works for every question,  I don't have many complaints on this but consider other ways to do this with recursion 
1. you used an array for the alphabet and a string for the special characters. I'd probably make these uniform.

**Comment by chong0810** [comment]
1, Moved scripts/js to assets
2. changed prompts to confirm dialog
3. do/while statements replaced
4. array changed to string and made them uniform
